# Assignment 1 - Working with NumPy


In [23]:
import numpy as np

## 1. Create a 1D NumPy Array and Perform Basic Statistics

**Step**: We use `np.arange(1, 21)` to create a 1D array containing integers from 1 to 20.  
**Purpose**: To practice generating sequences and computing basic statistics.

We then perform the following operations:

- `np.sum()` → Calculates the total sum of all elements.
- `np.mean()` → Computes the average value of the array.
- `np.median()` → Returns the middle value of the sorted array.
- `np.std()` → Calculates the standard deviation, indicating how spread out the values are.

Next, we use `np.where(arr > 10)` to find the **indices of all elements greater than 10**.  
This helps us practice conditional filtering and indexing in NumPy.


In [24]:
# 1 Create a 1D NumPy array with integers from 1 to 20
arr = np.arange(1, 21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [25]:
# a. Calculate sum, mean, median, and standard deviation
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("median",np.median(arr))
print('standard deviation',np.std(arr))


Sum: 210
Mean: 10.5
median 10.5
standard deviation 5.766281297335398


In [26]:
#b. Find the indices of elements greater than 10 in the array. 
greater_elemens = np.where(arr>10)[0]
print('greatr elements than 10 are:',greater_elemens)

greatr elements than 10 are: [10 11 12 13 14 15 16 17 18 19]


## 2. Create and Analyze a 2D NumPy Array

**Step**: We create a 2D array with values from 1 to 16 using `np.arange(1, 17)` and reshape it into a 4x4 matrix using `.reshape(4, 4)`.

**Purpose**: This helps us understand how to create and reshape arrays into multiple dimensions.

We then perform the following tasks:

- **Print the original array** for reference.
- **Transpose** the array using `.T`, which switches rows and columns.  
- **Row-wise sum** using `arr.sum(axis=1)` to add elements across each row.
- **Column-wise sum** using `arr.sum(axis=0)` to add elements down each column.

These operations show how NumPy handles axis-based calculations in 2D structures.


In [27]:
#2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  
arr_2d = np.arange(1,17).reshape(4,4)


In [28]:
# a. Print the array. 
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [29]:
#  b. Find the transpose of the array.  
transpose = arr_2d.T
print(transpose)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [30]:
# c. Calculate the row-wise and column-wise sums of the array.  
sum_of_rows =arr_2d.sum(axis=0)
print('row-wise  sum:',sum_of_rows)

sum_of_column =arr_2d.sum(axis=1)
print('column-wise sum:',sum_of_column)

row-wise  sum: [28 32 36 40]
column-wise sum: [10 26 42 58]


## 3. Element-wise and Matrix Operations on Random 3×3 Arrays

**Step**: We generate two 3x3 arrays filled with random integers between 1 and 20 using `np.random.randint(1, 21, size=(3, 3))`.

**Purpose**: To practice generating random matrices and applying operations on them.

We perform:

### a. Element-wise Operations:
- `arr1 + arr2`: Adds each corresponding element.
- `arr1 - arr2`: Subtracts each element in `arr2` from `arr1`.
- `arr1 * arr2`: Multiplies each pair of corresponding elements.

These operations demonstrate how broadcasting and element-wise math works in NumPy.

### b. Dot Product:
- `np.dot(arr1, arr2)` computes the **matrix product** (dot product) between the two arrays.  
This operation is essential in linear algebra, especially in machine learning and scientific computing.


In [31]:
#3. Create two 3 X 3 arrays filled with random integers between 1 and 20.  
arr1 =  np.random.randint(1,20,size=(3,3))
arr2 =  np.random.randint(1,20,size=(3,3))
print('Array 1:\n',arr1)
print('Array 2:\n',arr2)

Array 1:
 [[16  1 15]
 [ 2  9 11]
 [16  8 10]]
Array 2:
 [[ 3 15 15]
 [16 10  2]
 [18 17 19]]


In [32]:
#a. Perform element-wise addition, subtraction, and multiplication.

print('Element wise addition:\n ',arr1 +arr2)
print('Element wise subtraction:\n ',arr1 -arr2)
print('Element wise multiplication:\n ',arr1 * arr2)


Element wise addition:
  [[19 16 30]
 [18 19 13]
 [34 25 29]]
Element wise subtraction:
  [[ 13 -14   0]
 [-14  -1   9]
 [ -2  -9  -9]]
Element wise multiplication:
  [[ 48  15 225]
 [ 32  90  22]
 [288 136 190]]


In [33]:
#b. Compute the dot product of the two arrays.
print("dot product are:\n",np.dot(arr1,arr2))

dot product are:
 [[334 505 527]
 [348 307 257]
 [356 490 446]]


## 4. Reshape and Slice a 2D Array

**Step**: Create a 1D array with 12 elements using `np.arange(1, 13)` and reshape it into a 3x4 array using `.reshape(3, 4)`.

**Purpose**: To practice reshaping arrays and using slicing to extract specific elements.

Then we perform slicing:

- `[:2, -2:]` → selects the **first two rows** and the **last two columns** of the reshaped array.

This demonstrates how slicing in NumPy works across multiple dimensions using row and column indexing.


In [34]:
#4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows
#  and last two columns.  
new_arr =np.arange(1,13)

reshaped_arr = new_arr.reshape(3,4)

sliced =  reshaped_arr[:2,:-2]
print('The array is \n',new_arr)
print('Reshaped Aray into 3 X 4 \n',reshaped_arr) 
print("\nSliced (first 2 rows, last 2 columns):\n", sliced)

The array is 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Aray into 3 X 4 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced (first 2 rows, last 2 columns):
 [[1 2]
 [5 6]]
